session_name: odin
windows:
- window_name: odin
  layout: tiled
  shell_command_before:
    - cd ../src
    - source ~/.bashrc
  panes:
    - shell_command: # Densenet100
      - python main.py --nn densenet10 --dataset Uniform --magnitude 0.0014 --temperature 1000
      - sleep 5s
      - python main.py --nn densenet10 --dataset Gaussian --magnitude 0.0014 --temperature 1000
      - sleep 5s
      - python main.py --nn densenet10 --dataset SVHN --magnitude 0.0014 --temperature 1000
      - sleep 5s
    - shell_command: # Densenet10
      - sleep 5s
      - python main.py --nn densenet100 --dataset Uniform --magnitude 0.0028 --temperature 1000
      - sleep 5s
      - python main.py --nn densenet100 --dataset Gaussian --magnitude 0.0028 --temperature 1000
      - sleep 5s
      - python main.py --nn densenet100 --dataset SVHN --magnitude 0.0028 --temperature 1000
      - sleep 5s
    - shell_command: # IND
      - sleep 10s
      - python main.py --nn densenet10 --dataset cifar10 --magnitude 0.0014 --temperature 1000
      - sleep 5s
      - python main.py --nn densenet100 --dataset cifar100 --magnitude 0.0028 --temperature 1000
      - sleep 5s

